# syntax=docker/dockerfile:1.6
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.20.5-bookworm AS builder

ARG GOPROXY=
ARG HTTP_PROXY=
ARG HTTPS_PROXY=

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      binutils \
      cmake \
      gcc \
      libfindbin-libs-perl \
      libssh2-1-dev \
      libssl-dev \
      zlib1g-dev && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /tmp/build && \
    cd /tmp/build && \
    wget https://github.com/libgit2/libgit2/archive/refs/tags/v1.3.0.tar.gz -O - | tar -xz && \
    cd libgit2-1.3.0 && \
    mkdir build && \
    cd build && \
    cmake .. \
      -DBUILD_SHARED_LIBS=ON \
      -DBUILD_TESTS=OFF \
      -DCMAKE_INSTALL_PREFIX=/usr/local && \
    make -j"$(nproc)" install && \
    ldconfig

RUN go install github.com/vektra/mockery/v2@v2.20.0 && \
    go install github.com/swaggo/swag/cmd/swag@v1.16.1

WORKDIR /app
COPY . /app

ENV GOBIN=/app/bin

ARG TAG=main
ARG SHA=local
ARG DEVLAKE_PLUGINS=github,github_graphql,gitextractor,org,dora,issue_trace,refdiff,jira,webhook,jenkins

RUN --mount=type=cache,target=/root/.cache/go-build \
    VERSION="${TAG}@${SHA}" make build-server

RUN --mount=type=cache,target=/root/.cache/go-build \
    set -eux; \
    printf '#!/bin/sh\nprintf "2\\n"\n' > /usr/local/bin/nproc; \
    chmod +x /usr/local/bin/nproc; \
    DEVLAKE_PLUGINS="${DEVLAKE_PLUGINS}" make build-plugin; \
    rm -f /usr/local/bin/nproc

FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      ca-certificates \
      corkscrew \
      curl \
      git \
      libssh2-1 \
      libssl3 \
      openssh-client \
      tar \
      tini \
      zlib1g && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash -d /app devlake -u 1010 && \
    chown -R devlake:devlake /etc/ssl/certs

WORKDIR /app

COPY --from=builder /usr/local/lib/libgit2.so* /usr/local/lib/
RUN ldconfig

COPY --from=builder /app/bin ./bin
COPY --from=builder /app/resources ./resources

RUN mkdir -p logs python/plugins && \
    chown -R devlake:devlake /app

USER devlake

ENV LD_LIBRARY_PATH=/usr/local/lib
ENV PATH="/app/bin:${PATH}"
ENV PORT=8080
ENV PYTHONUNBUFFERED=1

EXPOSE 8080
VOLUME /app/logs

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["lake"]
